name: Contrib Repo Tests

on:
  push:

jobs:
  build:
    env:
      # We use these variables to convert between tox and GHA version literals
      py36: 3.6
      py37: 3.7
      py38: 3.8
      py39: 3.9
      RUN_MATRIX_COMBINATION: ${{ matrix.python-version }}-${{ matrix.package }}-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false  # ensures the entire test matrix is run, even if one permutation fails
      matrix:
        python-version: [ py36, py37, py38, py39 ]
        os: [ ubuntu-20.04 ]
    steps:
      - name: Checkout Contrib Repo @ SHA - ${{ github.sha }}
        uses: actions/checkout@v2
      - name: Set up Python ${{ env[matrix.python-version] }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env[matrix.python-version] }}
      - name: Install tox
        run: pip install -U tox-factor
      - name: run tox
        run: tox -e '${{ matrix.python-version }}-{flask,django21,psycopg2}'
        working-directory: ./python/sqlcommenter-python

